# PyTorch

In [1]:
import torch
import numpy as np

In [9]:
I = np.eye(3)
a = np.array([[-1, 0, -1], [-1, -1, -1], [1, 0, 1]])
ans = np.dot(I, a)
ans = np.dot(ans, a)
ans

array([[-1.,  0., -1.],
       [-1., -1., -1.],
       [ 1.,  0.,  1.]])

In [10]:
np.dot(a,a)

array([[0, 0, 0],
       [1, 1, 1],
       [0, 0, 0]])

In [12]:
b = np.array([[-2, 0, -1], [-1, -2, -1], [1, 0, 0]])
c = np.array([[0, 0, -1], [-1, 0, -1], [1, 0, 2]])
ans_2 = np.dot(b, c)
ans_2

array([[-1,  0,  0],
       [ 1,  0,  1],
       [ 0,  0, -1]])

In [2]:
6.022*6.6261*2.9979/457.5

0.26147175434793446

In [5]:
from math import e
e

2.718281828459045

In [11]:
e = e

In [103]:
T = 298

In [104]:
k = 2.45 * e**(-1775/T) 
k

0.006343733432497235

In [105]:
L = k*5 * 10**(-7)
L

3.1718667162486176e-09

In [106]:
s = 1/(L)

In [107]:
s/60/60/24

3648.97869597837

In [3]:
x = torch.empty(4,3)
print(x)

tensor([[1.9969e+16, 3.0614e-41, 2.0013e+16],
        [3.0614e-41, 8.9683e-44, 0.0000e+00],
        [1.1210e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 3.9848e+15, 4.5614e-41]])


In [4]:
x = torch.rand(5,3)
x

tensor([[0.9222, 0.8647, 0.9398],
        [0.4944, 0.8539, 0.4564],
        [0.2374, 0.0828, 0.8790],
        [0.3915, 0.2496, 0.6469],
        [0.8313, 0.2767, 0.0204]])

In [7]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


In [8]:
torch.tensor([[1,2], [3,4]])

tensor([[1, 2],
        [3, 4]])

In [9]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
print(x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.float64


In [11]:
x = torch.rand_like(x, dtype=torch.float)
x

tensor([[0.3549, 0.5712, 0.1468],
        [0.7072, 0.8822, 0.2382],
        [0.3250, 0.5576, 0.3414],
        [0.2965, 0.5234, 0.6329],
        [0.1620, 0.2567, 0.4772]])

In [13]:
x = torch.arange(0,19,0.5)
x

tensor([ 0.0000,  0.5000,  1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,
         4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,
         8.0000,  8.5000,  9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000,
        12.0000, 12.5000, 13.0000, 13.5000, 14.0000, 14.5000, 15.0000, 15.5000,
        16.0000, 16.5000, 17.0000, 17.5000, 18.0000, 18.5000])

In [15]:
x = torch.linspace(0,3,30)
x

tensor([0.0000, 0.1034, 0.2069, 0.3103, 0.4138, 0.5172, 0.6207, 0.7241, 0.8276,
        0.9310, 1.0345, 1.1379, 1.2414, 1.3448, 1.4483, 1.5517, 1.6552, 1.7586,
        1.8621, 1.9655, 2.0690, 2.1724, 2.2759, 2.3793, 2.4828, 2.5862, 2.6897,
        2.7931, 2.8966, 3.0000])